In [4]:
import pandas as pd

sales_data = pd.read_csv('Sales.csv')
sales_data.head()

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000

In [6]:
sales_data.iloc[:,0].nunique()

17

In [9]:
sales_data.iloc[sales_data.iloc[:,7].idxmax()]

Brands                                    Apple
Models                       iPhone 13 Pro Max
Colors                                     Gold
Memory                                     6 GB
Storage                                    1 TB
Camera                                      Yes
Rating                                      NaN
Selling Price                            179900
Original Price                           179900
Mobile                 Apple iPhone 13 Pro Max
Discount                                      0
discount percentage                         0.0
Name: 323, dtype: object

In [10]:
sales_data.iloc[sales_data.iloc[:,7].idxmin()]

Brands                     Nokia
Models                       105
Colors                     Black
Memory                      4 MB
Storage                     4 MB
Camera                       Yes
Rating                       4.3
Selling Price               1000
Original Price              1000
Mobile                 Nokia 105
Discount                       0
discount percentage          0.0
Name: 1501, dtype: object

In [11]:
sales_data.loc[0:26]

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,SAMSUNG,GALAXY M31S,Mirage Black,8 GB,128 GB,Yes,4.3,19330,20999,SAMSUNG GALAXY M31S,1669,7.947998
1,Nokia,3.2,Steel,2 GB,16 GB,Yes,3.8,10199,10199,Nokia 3.2,0,0.000000
2,realme,C2,Diamond Black,2 GB,NaN,Yes,4.4,6999,7999,realme C2,1000,12.501563
3,Infinix,Note 5,Ice Blue,4 GB,64 GB,Yes,4.2,12999,12999,Infinix Note 5,0,0.000000
4,Apple,iPhone 11,Black,4GB,64 GB,Yes,4.6,49900,49900,Apple iPhone 11,0,0.000000
5,GIONEE,L800,Black,8 MB,16 MB,Yes,4.0,2199,2199,GIONEE L800,0,0.000000
6,Apple,iPhone 13 Mini,Pink,6 GB,512 GB,Yes,NaN,99900,99900,Apple iPhone 13 Mini,0,0.000000
7,Apple,iPhone XR,Coral,3 GB,64 GB,Yes,4.6,42999,47900,Apple iPhone XR,4901,10.231733
8,SAMSUNG,Galaxy E5,Brown,1.5 GB,16 GB,Yes,4.2,20400,20400,SAMSUNG Galaxy E5,0,0.000000
9,Xiaomi,Redmi Note 11T 5G,Aquamarine Blue,8 GB,128 GB,Yes,4.3,21736,22999,Xiaomi Redmi Note 11T 5G,1263,5.491543
10,SAMSUNG,Galaxy A12,Black,4 GB,64 GB,Yes,4.2,11989,11989,SAMSUNG Galaxy A12,0,0.000000
11,Apple,iPhone 11,Red,4GB,256 GB,Yes,4.6,64900,64900,Apple iPhone 11,0,0.000000
12,realme,X7 5G,Nebula,6 GB,128 GB,Yes,4.3,19999,21999,realme X7 5G,2000,9.091322
13,OPPO,A33,Moonlight Black,3 GB,32 GB,Yes,4.3,10490,12990,OPPO A33,2500,19.245574
14,vivo,V23 5G,Sunshine Gold,8 GB,128 GB,Yes,4.4,29990,34990,vivo V23 5G,5000,14.289797
15,vivo,Y20A 2021,Nebula Blue,NaN,64 GB,Yes,3.8,39990,46990,vivo Y20A 2021,7000,14.896787
16,Apple,iPhone 13 Mini,Pink,6 GB,512 GB,Yes,NaN,99900,99900,Apple iPhone 13 Mini,0,0.000000
17,SAMSUNG,Galaxy J2 Core,Gold,1 GB,16 GB,Yes,4.2,6999,6999,SAMSUNG Galaxy J2 Core,0,0.000000
18,Lenovo,K10 Plus,Sprite,4 GB,64 GB,Yes,4.1,13999,13999,Lenovo K10 Plus,0,0.000000
19,ASUS,Zenfone Max,Blue,2 GB,32 GB,Yes,4.1,7699,7699,ASUS Zenfone Max,0,0.000000
20,Motorola,M,Grey,4 GB,64 GB,Yes,3.9,9999,9999,Motorola M,0,0.000000
21,realme,1,Diamond Black,3 GB,NaN,Yes,NaN,11990,12990,realme 1,1000,7.698229
22,GIONEE,Pioneer P4S,White,1 GB,8 GB,Yes,3.5,3499,3499,GIONEE Pioneer P4S,0,0.000000
23,realme,X3,Arctic White,6 GB,128 GB,Yes,4.4,24999,26999,realme X3,2000,7.407682
24,realme,Narzo 30A,Laser Blue,3 GB,NaN,Yes,4.3,8999,9999,realme Narzo 30A,1000,10.001000
25,realme,8 Pro,Illuminating Yellow,6 GB,NaN,Yes,4.3,17999,19999,realme 8 Pro,2000,10.000500
26,GIONEE,F205 Pro,Black,2 GB,16 GB,Yes,4.1,6990,6990,GIONEE F205 Pro,0,0.000000

In [13]:
sales_data.isnull()

,Brands,Models,Colors,Memory,Storage,Camera,Rating,Selling Price,Original Price,Mobile,Discount,discount percentage
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
3109,False,False,False,False,False,False,False,False,False,False,False,False
3110,False,False,False,True,False,False,False,False,False,False,False,False
3111,False,False,False,False,False,False,False,False,False,False,False,False
3112,False,False,False,False,False,False,True,False,False,False,False,False
3113,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
sales_data["Memory"].fillna(sales_data["Memory"].mode()[0], inplace=True)
sales_data["Storage"].fillna(sales_data["Storage"].mode()[0], inplace=True)

print(sales_data[["Memory", "Storage"]].isnull().sum())

Memory     0
Storage    0
dtype: int64

In [19]:
sales_data.groupby('Brands')['Models'].value_counts()

Brands  Models
ASUS    Zenfone Selfie         16
        Zenfone Max Pro M1     10
        Zenfone Go              8
        6Z                      7
        ZenFone Max M2          6
                               ..
vivo    Y83                     1
        Y90                     1
        Y91i                    1
        Y93                     1
        Y94                     1
Name: count, Length: 928, dtype: int64

In [ ]:
sales_data.groupby('Brands')['Discount'].max().sort_values()

In [22]:
sales_data.groupby('Brands')['Selling Price'].sum().sort_values(ascending=False)

Brands
Apple           31728412
SAMSUNG         17469003
realme           5361667
OPPO             4825727
Xiaomi           3354498
vivo             2959414
ASUS             2398576
Nokia            2008304
LG               1912995
Google Pixel     1780364
Motorola         1717534
Infinix          1674919
HTC              1557291
POCO             1248426
Lenovo           1220145
GIONEE            920427
IQOO              185950
Name: Selling Price, dtype: int64